name: httpjpg
options:
  bundleIdPrefix: com.yl33ly
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  minimumXcodeGenVersion: "2.38.0"

configs:
  Debug: debug
  Release: release

packages:
  httpjpg-kit:
    path: httpjpg-kit

fileGroups:
  - Config
  - README.md

targets:
  httpjpg:
    type: application
    platform: iOS
    sources:
      - path: httpjpg
    dependencies:
      - package: httpjpg-kit
        product: DesignSystem
      - package: httpjpg-kit
        product: StoryblokContent
      - package: httpjpg-kit
        product: PortfolioFeature
      - package: httpjpg-kit
        product: WidgetFeature
      - target: httpjpg-widgets
        embed: true
    configFiles:
      Debug: Config/Shared.xcconfig
      Release: Config/Shared.xcconfig
    settings:
      base:
        INFOPLIST_FILE: httpjpg/Info.plist
        GENERATE_INFOPLIST_FILE: true
        ENABLE_PREVIEWS: true

  httpjpg-widgets:
    type: app-extension
    platform: iOS
    sources:
      - path: httpjpg-widgets
    dependencies:
      - package: httpjpg-kit
        product: DesignSystem
      - package: httpjpg-kit
        product: StoryblokContent
      - package: httpjpg-kit
        product: WidgetFeature
    configFiles:
      Debug: Config/Widgets.xcconfig
      Release: Config/Widgets.xcconfig
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
